#!/usr/bin/env bash


# Check for bucket name
if [ -z "$1" ]; then
    echo "There needs to be a bucket name eg. ./bucket my-bucket-name"
    exit 1
fi

Bucket_Name=$1

echo "aws s3api create-bucket --bucket $Bucket_Name"

aws s3api create-bucket --bucket $Bucket_Name